//  chapter.swift
//  PodcastClient
//
//  Created by Holger Krupp on 01.12.23.
//

import Foundation
import SwiftData
import SwiftUI

enum MarkerType: String, Codable, Comparable{
    static func < (lhs: MarkerType, rhs: MarkerType) -> Bool {
        lhs.desc < rhs.desc
    }
    
    case podlove
    case mp4
    case extracted
    case unknown
    case mp3
    case ai
    case bookmark
    
    var desc:String{
        
        switch self {
        case .podlove:
            "These Chapters have been extracted from the feed following Podlove Simple Chapter Specification."
        case .ai:
            "These Chapters have been generated by AI through the transcript of the podcast episode."
        case .mp3:
            "These Chapters have been extracted from the mp3 file."
        case .mp4:
            "These Chapters have been extracted from the m4a file."
        case .extracted:
            "These Chapters have been extracted from the shownotes using RegEx. They might contain errors. Inserted ads might shift the start and end times of chapters by several minutes."
        case .unknown:
            ""
        case .bookmark:
            "Bookmarks can be created when listening to an episode."

        }
        
    }
    
    
}
@Model
class Marker: Identifiable, Equatable, Hashable{
    
    
    var id = UUID()
    var title: String = ""
    var link: URL?
    var image: URL?
    var imageData:Data?
    var start: Double?
    var endTime: Double?
    var duration: TimeInterval?
    var creationtime:Date? = Date()
    @Relationship(inverse: \Episode.chapters) var episode: Episode?
    @Relationship(inverse: \Episode.bookmarks) var bookmarkEpisode: Episode?

    
    var progress:Double? // 0 -1 
    
    @Transient var remainingTime: TimeInterval? {
        guard let duration = duration, let progress = progress else { return nil }
        return max(0, duration * (1 - progress))
    }
    
    @Transient var end:Double? {
        if endTime != nil{
            return endTime
        }else{
            let end = ((start ?? 0) + (duration ?? 0))
            if end > 0{
                return end
            }else{
                return nil
            }
        }
    }
    
    
    var type : MarkerType = MarkerType.unknown
    
    var shouldPlay:Bool = true
    
    
    @Transient var didSkip:Bool = false
    
    
 
    
    
    init(){}
    
    init(details: [String: Any]) {
        title = details["title"] as? String ?? ""
        start = (details["start"] as? String)?.durationAsSeconds
        endTime = (details["endTime"] as? Double)
        if let endTime, let start{
            duration = endTime - start
        }
        
        link = URL(string: details["href"] as? String ?? "")
        image = URL(string: details["image"] as? String ?? "")
        if let imagedata = (details["APIC"] as? [String:Any])?["Data"] as? Data{
            // print("ImageChapter with Image data")
            imageData = imagedata
        }
        type = .podlove
        
    }
    
    init(start: Double, title: String, type: MarkerType? = .unknown, imageData: Data? = nil, duration: TimeInterval? = nil){
        self.start = start
        self.title = title
        self.type = type ?? .unknown
        self.imageData = imageData
        self.duration = duration
        if let duration{
            self.endTime = start + duration
        }
        
        // print("init Marker \(title)")
    }
    
    static func ==(lhs: Marker, rhs: Marker) -> Bool {
        
        if lhs.episode != rhs.episode, lhs.episode != nil{
            return false
        }else if lhs.type != rhs.type{
            return false
        }else if lhs.id == rhs.id{
            return true
        }else{
            return false
        }
        
        
    }
    func hash(into hasher: inout Hasher) {
        
        hasher.combine(id)
    }
}
